### ISSUE TITLE
UnhandledPromiseRejectionWarning: koa' do not define a valid '.' target

### ISSUE THREAD

**Issue by nexflo** [johannschopplich/kirby-vue3-starterkit#1]
After npm install and npm run start this gets thrown

vite v1.0.0-rc.4
[1] (node:55150) UnhandledPromiseRejectionWarning: Error: Package exports for 'kirby-vue3-starterkit-master/node_modules/koa' do not define a valid '.' target

node v13.1.0

**Comment by johannschopplich** [comment]
I can't reproduce that. Seems like an error specific to your setup. What do you use?

I have tested the app locally on Windows, macOS as well as Linux successfully. Although in each case on Node 14+.

**Comment by nexflo** [comment]
Yea Node 14 fixes it.
