### ISSUE TITLE
Panel not reachable

### ISSUE THREAD

**Issue by TobeyEh** [johannschopplich/kirby-vue3-starterkit#10]

**Comment by johannschopplich** [comment]
Hey there, the setup may seem quite complex, especially if you're new to Vue. To sum up:
- The panel is reachable via `127.0.0.1:3000/panel` (with default configuration)
- The frontend is reachable via `localhost:3000`

You can build your assets, serve the application and then take a look at how the compiled app for production is rendered by visiting `127.0.0.1:3000`. This is similar to visiting the website later on a production server.

Have fun!
