### ISSUE TITLE
<script> container exposing titles and listing status of all the top level pages as JSON

### ISSUE THREAD

**Issue by TobeyEh** [johannschopplich/kirby-vue3-starterkit#12]
Hi there Johann! Thanks for the starterkit, works like a charm! Thanks again for the great work! 

I have one question though: after building the site there's a `<script>` container left in the body tag exposing the titles, templates and listing statuses of **all** the top level pages as JSON, even the unpublished/hidden ones. 

Is this on purpose? Because it leaves all the top level pages' info fully exposed to the public regardless if they're hidden pages or not. Like if I had a page I wanted to hide from the public, its URL etc. is still visible to the public and therefore still accessible (if set to "unlisted").

Or am I building it wrong? 

Example:

```
<script id="site-data" type="application/json">
   {"children":[{"uri":"arbeiten","title":"Arbeiten","isListed":true,"template":"arbeiten","childTemplate":"arbeit"},
   {"uri":"publikationen","title":"Publikationen","isListed":true,"template":"publikationen","childTemplate":"publikation"},
   {"uri":"biografie","title":"Biografie","isListed":true,"template":"biografie","childTemplate":null},
   {"uri":"kontakt","title":"Kontakt","isListed":true,"template":"kontakt","childTemplate":null},
   {"uri":"error","title":"Error","isListed":false,"template":"error","childTemplate":null},
   {"uri":"home","title":"Home","isListed":false,"template":"home","childTemplate":null}],"languages":[],"title":"123"}
</script>
```

**Comment by johannschopplich** [comment]
Hi there, thanks for the verbose issue and your compliment. I'm excited you're using my starterkit for one of your projects!

You're doing everything right. The `<script id="site-data" type="application/json">` is required to [populate the Vue Router](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/ffb2d6fb60f59d358315a16b13e000015e382b61/frontend/src/router/index.js#L17) with routes upon the first request. Inlining the top-level children of the site is more performant than calling an additional route upon first request just for routes data.

In a traditional Vue SPA all routes would have to be defined for the router by hand, which are visible publicly as well. Example:
```js
const router = new VueRouter({
  routes: [
    { path: '/foo', component: Foo },
    { path: '/bar', component: Bar }
  ]
})
```

In this boilerplate, the routes will be dynamically generated by [`spa-site.json`](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/ffb2d6fb60f59d358315a16b13e000015e382b61/site/config/spa-site.php#L6) and parsed by the Vue Router.

By the way, the frontend navigation or a sitemap will also "expose" routes. It's not something to hide necessarily. 

I agree tho, some unlisted pages might want to be hidden from sitemaps etc. and in the same way from the routing JSON. But that's not possible at the moment: Every route has to be matched with its Vue component (view) on the Vue initialization. All other routes will fall back to the `default` template.

If you truly want to unlisted pages, you can adapt the `spa-site.php` by:
```diff
return [
    'children' => array_values(
        site()
            ->children()
-            ->published()
+            ->filter(fn($child) => $child->isHomePage() || $child->isListed())
            ->map(fn($child) => [
            // ...
```

Keep in mind, that with this change unlisted pages will keep to be accessible, but will not work if they use templates other than `default`.

Hope that answers your question.

Would be happy if you drop me a line once the project is live. Eager to see it. 🙂

**Comment by TobeyEh** [comment]
Hi Johann, thanks for your very swift reply! Makes perfect sense 😃  I'll leave it then.

While I have you here, do you maybe know what might cause this debug error? (Sorry if this is a silly question, it's my first Vue project.)

`No hashed build asset found for style.css. Make sure it's bundled by Vite.`

in: 

```
public static function pathToAsset (string $filename): string
    {
        $hashedFilename = static::useManifest()[$filename] ?? null;
        if ($hashedFilename === null) {
            throw new Exception("No hashed build asset found for {$filename}. Make sure it's bundled by Vite.");
        }
 
        return static::useAssetsDir() . '/' . $hashedFilename;
    }
```

at: 

`/site/plugins/kirby-spa-adapter/classes/SpaAdapter.php`

Thanks!

**Comment by johannschopplich** [comment]
If it's your first Vue project I recommend you read the docs and test a Vue setup outside of my starterkit, because the starterkit itself build upon some amount of Vue knowledge.

Could you pull the latest changes? `style.css` has been renamed to `index.css` since Vite 2. So just rename it in the `spa-index.php`.
I've made some changes over the last couple of days. Would be best to start off fresh.

**Comment by TobeyEh** [comment]
I made the Mozilla Vue tutorial project and watched other tutorials. It's working well so far. 😃 
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

Yeah, I'll post a link. Anyways, thanks and have nice new year!
