### ISSUE TITLE
Page nesting

### ISSUE THREAD

**Issue by TobeyEh** [johannschopplich/kirby-vue3-starterkit#14]
Successfully finished a site a couple days ago with your starterkit – thx, worked great!

Concerning another project: is the following nesting structure supported by your starterkit: 

```
Page 1
Page 2
Page 3
   |
   Page 3.1
   Page 3.2
      |
      Page 3.2.1
      Page 3.2.2
      Page 3.2.3
```

Urls would then be for example
    www.example.com/cities/rome/theatres
    www.example.com/cities/rome/museums
    www.example.com/cities/rome/restaurants

Or is the nesting limited to for example 
    www.example.com/cities/rome

Thanks again!

(Sorry, don't know how to add the github "question" label.)

**Comment by johannschopplich** [comment]
You can add nested levels by yourself.

1. Edit: https://github.com/johannschopplich/kirby-vue3-starterkit/blob/fa9bc8c3e8aaacd60e505b8750481e2ef70559b2/frontend/src/router/index.js#L17
```js
const routes = [
  // ...
  // Add these lines below the `site.children` spreaded array
  ...site.grandchildren
    .filter(page => page.childTemplate)
    .map(page => ({
      path: `/${page.uri}/:id`,
      component: () => import(`../views/${capitalize(page.childTemplate)}.vue`).catch(() => Default)
    }))
]
```

2. Add grand children below `children` key: https://github.com/johannschopplich/kirby-vue3-starterkit/blob/fa9bc8c3e8aaacd60e505b8750481e2ef70559b2/site/config/spa-site.php#L6

```php
'grandchildren' => array_values(
  site()
      ->grandChildren()
      ->published()
      ->map(fn($child) => [
          'uri' => $child->uri(),
          'title' => $child->title()->value(),
          'isListed' => $child->isListed(),
          'template' => $child->intendedTemplate()->name(),
          'childTemplate' => $child->hasChildren() ? $child->children()->first()->intendedTemplate()->name() : null
      ])
      ->data()
),
```

3. Have fun!

**Comment by johannschopplich** [comment]
@TobeyEh I'm curious. Did you succeeded implementing nested pages?

**Comment by TobeyEh** [comment]
Hi, wow, thanks I will try it asap! The kirby panel structure has not been set up yet so I couldn't test is yet. Later this evening though. I just wanted to ask in advance if it's even possible, if not I would have just used the non-Vue starterkit.

**Comment by johannschopplich** [comment]
Cool! No rush. It's a good question. If I write dedicated docs one day, I'll put in in the FAQ section. 

As I said, haven't tested locally myself, but it should work. Every route level has to be passed to the router, I've only included two levels as default – similar to the starterkit.

**Comment by TobeyEh** [comment]
Hey! I have only tested it locally in a very simple setup but it really seems to work! 🎉
Thanks again for your great starterkit support! I will keep you posted concerning the level nesting.
