### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by Mark-Pilkington** [johannschopplich/kirby-vue3-starterkit#15]
No issue, just an info maybe for the docs: 
In order to make the multi-language work, you have to run `npm run build` first. 
If you run `npm run dev` it won't resolve the multi language paths but throw a `404 error` on the `json` file.
 
From the starterkit: 
`Unhandled Promise Rejection: Error: The requested URL /en/viteproxy/spa/photography.json failed with response error "Not Found".`
or
`Unhandled Promise Rejection: Error: The requested URL /en/viteproxy/spa/__site.json failed with response error "Not Found".
`

So on local, the multi-language works on `127.0.0.1` but not on `localhost`.

**Comment by johannschopplich** [comment]
`/en/viteproxy/` should be `/viteproxy/en/` instead. That's why local development isn't working...

Have you enabled multi-lang by setting `KIRBY_MULTILANG` to `true` in your dot env file?

**Comment by Mark-Pilkington** [comment]
Yeah, I didn't change anything except enabling the multi-language options in the .env and added the languages in the panel. I also set the port from 8080 to 3000.

**Comment by johannschopplich** [comment]
Good catch, it's a bug introduced when I upgraded to Vite 2 and had to introduce the `viteproxy` path prefix.

**Comment by Mark-Pilkington** [comment]
Ah ok, just wanted to let you know 😃 

Ah, while I have you here, lol – do you know maybe by heart if your starterkit allows custom language variables (for button translations or similar)?
[https://getkirby.com/docs/guide/languages/custom-language-variables](url)

They're stored inside the language file at `languages/en.php` so they're not part of the `json` files and have to be echoed via php `<?= t('change') ?>`

But maybe that's actually more a content representations question for the Kirby forum.

**Comment by johannschopplich** [comment]
@Mark-Pilkington That was a nasty bug. Thanks for reporting. Vite 2 disallows glob matching (`*`) in the proxy configuration. That's why I had to introduce the `viteproxy` path.

Please open a seperate issue for your question.
