### ISSUE TITLE
Language switch best practise?

### ISSUE THREAD

**Issue by Mark-Pilkington** [johannschopplich/kirby-vue3-starterkit#17]
Hi there! 

I have a multi-language setup and implementing a language switch. 

In the standard PHP Starterkit I'd use the language code inside the `url` constructor to construct the corresponding second language `url` (same destination/path):

     <a href="<?= $page->url(kirby()->language()->code('en')) ?>">
        English
     </a>

(Hardcoded language code/name to explain)

In the Vue Starterkit `router-link` I'm thinking about setting the `:to` by combining a `inactivelanguagecode` (set in `site-spa.php`) and the current `route.path`. 

            <router-link 
              :key="`${site.inactivelanguagecode + route.path}`"
              :to="`/${site.inactivelanguagecode + route.path}`"
              class="navigation__link"
            >
              <span>
                {{ site.inactivelanguagename }}
              </span>
            </router-link>

Is there a more proper and less hacky way?

Thanks!

EDIT: edited the `router-link`

**Comment by johannschopplich** [comment]
Hi there, great question!

Using `<router-link>` won't work, since we need a hard redirect. The Vue router is initialized with a base path, which is the language code in multi-lang setups. To redirect to another language we will have to re-visit the whole page and initialize the router again.

I've create an example language switcher component: https://github.com/johannschopplich/kirby-vue3-starterkit/commit/f01494175d8d45716ae9b8b0bb82476c83eed6ca

```vue
<template>
  <a
    v-for="lang in site.languages.filter(language => language.code !== currentCode)"
    :key="lang.code"
    :href="`/${lang.code}`"
  >
    {{ lang.name }}
  </a>
</template>

<script>
import { useSite, useLanguages } from '../hooks'

export default {
  setup () {
    const site = useSite()
    const { languageCode: currentCode } = useLanguages()

    return {
      site,
      currentCode
    }
  }
}
</script>
```

Hope that helps. Feedback appreciated.

**Comment by Mark-Pilkington** [comment]
Hey! Such a swift response – **thanks!** It works! 😃  

I had to change the 

    :href="`/${language.code}/${route.path}`"

to 

    :href="`/${language.code}${route.path}

without the second forward slash `/` otherwise the new URL has two forward slashes `//` before the path.
Like `www.example.com/en//somepage`

Thanks again for your fast handling!

**Comment by johannschopplich** [comment]
Glad to hear it works. 🙂 

Thanks, good catch. 👍 Changed: https://github.com/johannschopplich/kirby-vue3-starterkit/commit/9b96af2e44cb80aba6645598c308431df4ca459f
