### ISSUE TITLE
Custom CSS file path

### ISSUE THREAD

**Issue by Mark-Pilkington** [johannschopplich/kirby-vue3-starterkit#18]
Hi! If I wanted to have a custom `panel.css` file, do you maybe know what path I'd have to use? 

I tried a hardcoded `http://127.0.0.1:3000/static/css/panel.css` to a custom folder named "static" however unfortunately it's not loading into the `<head>` part of the panel though. The path is correct though. I don't actually know if it's an issue on my setup's side or a Vue Starterkit issue.

This is the `config.php` file's content:

```
    'panel' => [
        'install' => env('KIRBY_PANEL_INSTALL', false),
        'slug' => env('KIRBY_PANEL_SLUG', 'panel'),
        'css' => 'http://127.0.0.1:3000/static/css/panel.css'
    ],
```

Thanks! 😃 

https://getkirby.com/docs/reference/system/options/panel#custom-panel-css

**Comment by Mark-Pilkington** [comment]
Withdrawn, figured it out, it needs a relative path apparently.

**Comment by johannschopplich** [comment]
Jep, those should be relative paths based on the Kirby index route. Glad to hear you figured it out by yourself.
