### ISSUE TITLE
syntax error, unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by trych** [johannschopplich/kirby-vue3-starterkit#23]
Hi there!

I tried to get this running, followed the install instructions and when I am told to visit the app at [http://127.0.0.1:8080/](http://127.0.0.1:8080/), I get this error message:

```txt
syntax error, unexpected 'static' (T_STATIC)
```

![20210604-001121_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/120718321-6a8c9200-c4c9-11eb-9097-22993c617715.png)

I have no idea, what any of this means and how I can fix this. 😓 Any ideas?

Thanks!

**Comment by tobystokes** [comment]
Try switching to PHP 8+ if possible.
(I know the readme says only PHP 7.4 is required, but from the looks of it, there are some v8 features in the kirby-vue plugin)

**Comment by johannschopplich** [comment]
This starterkit is made for PHP 7.4+ environments and no features of PHP 8 are used (unless polyfillable features, then a Composer package may be used).

I can't replicate your error. I'm curious: Would you mind installing PHP 8 on your machine and running the starterkit again?

**Comment by tobystokes** [comment]
(@johannschopplich thanks for this super starterkit!) 
I have only just started to kick the tires, but I think in `site/plugins/kirby-vue/classes/KirbyVue/Vite.php`
those static return types are a PHP 8+ feature. I got the same error as @trych above when using PHP 7.4, but not on 8  - using Valet to switch php versions.

**Comment by tobystokes** [comment]
and fwiw, If I remove them from there and `site/plugins/kirby-vue/classes/KirbyVue/Page.php` then the rest all works under 7.4 no problem!

**Comment by johannschopplich** [comment]
@tobystokes Thank you for the insights and your tests! My bad that I've introduced a breaking change. Will fix that.

**Comment by johannschopplich** [comment]
Thank you both for the bug report! Should be fixed in https://github.com/johannschopplich/kirby-vue3-starterkit/commit/7193607c2ca4937a42bf29ba3bd2ed51f344dd4b and https://github.com/johannschopplich/kirby-vue3-starterkit/commit/608bdf4757e922c7486dcf1032c6556b8961d79e. 

Please test again, @trych.
