### ISSUE TITLE
Creating pages from frontend

### ISSUE THREAD

**Issue by parislettau** [johannschopplich/kirby-vue3-starterkit#24]
I'm trying to utilise the Kirby API to create pages using the front-end of Vue (with a form) — with the exact same purpose as described int this Cookbook recipe: https://getkirby.com/docs/cookbook/forms/creating-pages-from-frontend

Any guidance on how this is done via your Vue starterkit?

**Comment by johannschopplich** [comment]
Since the default Kirby templates are replaced by the Vue frontend in this starterkit, this cookbook is not applicable as-is.

You could instead create a custom API route, post data to it and then parse everything from within your custom route plugin.
