### ISSUE TITLE
Using Query Parameters or URL Parameters

### ISSUE THREAD

**Issue by degoya** [johannschopplich/kirby-vue3-starterkit#25]
At first i'd like to thank you for your great job with the vue3 starterkit.

now after i've started to work with your setup i'd like to include a seach, when i use the search from the cookbook it uses query parameters for the search. when i try something like this it doesn't work because of the changed routing the parameters are not available in the controller. 

can you tell me how to solve the problem using query parameters with your setup.

**Comment by johannschopplich** [comment]
You will have to implement a search component on the frontend-side yourself and fetch data from a custom backend API route. Or use the `usePage()` hook and embed the data on your page (not recommended, but possible).
Query parameters will probably not be needed in your reactive search component. 

You may hit up Google with search terms like “build vue search component” etc. Hope you will find something useful!

**Comment by degoya** [comment]
Thanks for your reply, the reactive part is not really a problem with a custom route, but i need the parameters in the url to make the searchpage shareable. Can't the route be changed to give the URL parameters to the controller? would you mind to maybe provide me a example? i'm new to both kirby and vue :)

**Comment by johannschopplich** [comment]
This setup may be a bit too complex if you're new to Kirby and Vue. I recommend learning a bit of both and then revisit this boilerplate. Since both are tightly integrated into another.

Sorry, but I can't give you support for such a specific request.

**Comment by degoya** [comment]
i solved it by using 

```
  $data = [
      'q' => get('q'),
    ];
  return page($page)->render($data);
```

insted of 

`            $html = kirby()->render(page($page));
            return $html;
`
inside the routes.php of the router plugin to pass the parameters to the controller

**Comment by degoya** [comment]
Solved the problem by using this.route.query.q in my vue and doing the search via the api with Vue.

used this is the search vue

...

```
 <input
    type="text"
    v-model.trim="search"
    placeholder="search ..."
    @keyup="getSearchResult"
/><br />
<ul>
    <li v-for="result in results" :key="result.id">
        {{ result.title }}
    </li>
<ul>
```

...


```
data() {
    return {
      results: [],
      search:  this.route.query.q
    };
  },
methods: {
    getSearchResult() {
      if(this.search) {
        fetch("/search/"+this.search.toLowerCase())
          .then(response => response.json())
          .then(res => {
            if (this.search) {
              this.results = res.results.filter(results =>
                results.title.toLowerCase().includes(this.search.toLowerCase())
              );
            } else {
              this.results = res.results;
            }
          });
      }
    }
  },
```

i've added this to the routes.php

```
    /**
     * Return JSON-encoded search data
     */
    [
        'pattern' => 'search/(:any)',
        'language' => '*',
        'action' => function ($any,...$args) {
            $query   = $any;
            if ($query) {
              $results = site()->search($query, 'title|text');
            }
            foreach ($results as $result):
                $results_array[] = array(
                    'url'=>$result->url(), 
                    'title'=>$result->title()->value()
                  );
            endforeach;
            $data = [
                'query' => html($query),
                'results' => $results_array,
              ];


            return \Kirby\Data\Json::encode($data);      
        }
    ],
```

maybe it's helpful for someone
