### ISSUE TITLE
Deployed vite scripts refers to localhost

### ISSUE THREAD

**Issue by Maybach91** [johannschopplich/kirby-vue3-starterkit#29]
I just cloned the project.

And did the steps in  the `README.md` (`composer install && npm install && cp .env.example .env && ln -s $PWD/src/assets ./public/assets`)

When running `npm i && npm run build` locally and then upload the whole repository (without node_modules) i can access the kirby backend on my server, but the fronted tries to access the following link. 

```html
  <script src="http://localhost:3000/@vite/client" type="module"></script> 

  <script src="http://localhost:3000/index.js" type="module"></script> 
```
Anything related to this line? [site/plugins/kirby-vue/classes/KirbyVue/Vite.php#L136](https://github.com/johannschopplich/kirby-vue3-starterkit/blob/e3f5d3a8d2b0996a48fbf2ddd6314218431bce0d/site/plugins/kirby-vue/classes/KirbyVue/Vite.php#L136)  
  
Since i only have a normal shared hosting server and no node server, i cannot run `npm i && npm run build` on the server as suggested in the `README.md`

Domain is pointing to `public/` and `KIRBY_PANEL_INSTALL=true` is set in the `.env` on the server.

What am i missing or doing wrong here?

Running `npm run dev` locally works fine.

**Comment by johannschopplich** [comment]
Building locally and deploying to the server should work just fine… Are you certain the `src/.lock` file is removed from the server? It handles embedding the dev script.

**Comment by Maybach91** [comment]
I just removed the src/.lock file, but it still doesnt work and the index tries to implement the localhost script. 
Do i have to setup the production `.env.production` locally and then run `npm run build` again and deploy then? I think i’m missing something, but i’m not sure what. I also have `KIRBY_DEBUG` set to `false` and then run `npm run build` locally again and uploaded everything again. But still the index file of my server (which points to public/) tries to implement the localhost file.

I think is has something to do that i cannot run node on my production server, right?

**Comment by johannschopplich** [comment]
Technically speaking it doesn't make a difference building for production locally or on the server. `npm run build` just bundles the frontend assets. 

You don't have to create a `.env.production`. Also, environment variables like `KIRBY_DEV_HOSTNAME` are solely needed for development.

I'm afraight I can't help you, since I don't insight into your hoster or server environment. I recommend using a shared hoster who has Node installed by default (I'm surprised there are some who haven't) so you can follow the tested installation step.s

**Comment by Maybach91** [comment]
Ah, thanks for the point! I just figured out i can install node on my server, i was using for years. :D 

I just deleted the public/ folder and run the scripts on the server and it now works. (i think it was more related to the contents of the public server instead of the build process ran on the server.

Thank you so much for your help @johannschopplich & the starter kit!
