### ISSUE TITLE
Enhancement: Sass?

### ISSUE THREAD

**Issue by nexflo** [johannschopplich/kirby-vue3-starterkit#3]
Being trying to activate sass...put running into multiple errors? Had the same issues?

**Comment by johannschopplich** [comment]
It's available. Please refer to the Vite documentation: https://github.com/vitejs/vite#css-pre-processors

**Comment by johannschopplich** [comment]
@nexflo Use Sass styles just like in any other project utilizing Vue. E.g.:
```js
import './styles.scss'
```

Or in a SFC:

```html
<style lang="scss">
</style>
