### ISSUE TITLE
(?) Best Practice: Using Tags for filtered Collections

### ISSUE THREAD

**Issue by Maybach91** [johannschopplich/kirby-vue3-starterkit#30]
When i want to have a filter for my projects, i cannot really use the parameters from kirby, since they are not there in the vue frontend, right? https://getkirby.com/docs/cookbook/content/filtering-with-tags#tagcloud

Is there any best practice how to implement something like this? 

I only can think of creating folders within `pages` and then "hard" linking my filter to these routes by lowercasing my tags? But that means the editor cannot create a new category by its own. 

When building a vue component for this, i need to have fetch the get parameters and showing content accordingly, but that also doesn’t feel right. 

Any ideas?

**Comment by johannschopplich** [comment]
You will have to create a Vue component for that specific use-case. The Vue Router docs may help you. I recommend using the `useRoute` hook to fetch params. Those can then be parsed and/or modified by your component. Then you will have to fetch the content manually.

Someone ran into a similar use-case a while ago: https://github.com/johannschopplich/kirby-vue3-starterkit/issues/25
