### ISSUE TITLE
Kirby caches path to assets?

### ISSUE THREAD

**Issue by tobystokes** [johannschopplich/kirby-vue3-starterkit#32]
With following `.env` settings:
```
KIRBY_CACHE=true
VITE_SERVICE_WORKER=true
VITE_STALE_WHILE_REVALIDATE=true
```

If I regenerate the assets with `npm run build`, the path in `<?= vite()->js() ?>` doesn't get updated to the latest hash specified in the manifest, because `_app-index.php` is cached.

Let me know if I'm misunderstanding something here! Would it be enough to just exclude the home page from ever being cached?

**Comment by johannschopplich** [comment]
That's default behaviour of Kirby and intended if you have caching enabled. When you rebuild, you will have to delete the cache manually. For example, run:

```bash
npm run build && rm -rf storage/cache/example
```

A simpler solution would be to add a custom script. Consider adapting your `package.json` with a script to delete your cache folder without having to manually adjust the `rm -rf` script:

```json
"scripts": {
  "kirby:flush-cache": "find storage/cache -maxdepth 1 -mindepth 1 -type d -exec rm -rf '{}' \\;",
  "build": "... && npm run kirby:flush-cache",
},
````
