### ISSUE TITLE
Vue.js devtools

### ISSUE THREAD

**Issue by fleshgordo** [johannschopplich/kirby-vue3-starterkit#38]
I wonder if you need to setup something specific in order to have the vue.js devtools up and running. The [plugin](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) I am usually using, doesn't indicate that the page uses vue.js unfortunately and the vuejs tab doesn't show up in the web inspector. Any hints?

**Comment by johannschopplich** [comment]
You will need one of the latest [Vue devtools versions](https://github.com/vuejs/devtools/releases/tag/v6.0.0-beta.21) for Vue.js 3 support.

The official ones are outdated.

**Comment by fleshgordo** [comment]
Thanks. works like charm!
