### ISSUE TITLE
/service-worker.js 404

### ISSUE THREAD

**Issue by mrflix** [johannschopplich/kirby-vue3-starterkit#4]
I'm trying to debug the service-worker offline but can't get the service-worker script to load with the vite dev server.
### How to reproduce:
- fresh install
- (edit `scripts/buildSw.js:3` `require('fs/promises')` to `require('fs').promises since the former breaks with node v12.18.3)
- (run `npm run build` – don't know if it's necessary at this stage)
- enable `VITE_ENABLE_SW` and `VITE_ENABLE_SWR` in `.env`
- run `npm run serve`

### Result
The service worker under `http://localhost:3000/service-worker.js` fails to load with a 404.

How are you debugging the service-worker locally?

**Comment by johannschopplich** [comment]
Honestly it's rather tricky to debug the service worker. You need at least a self-signed certificate or enable service workers for HTTP in your browser settings.

But even if done so, the service worker relies on the generated scripts. Vite doesn't bundle your application. It serves the waterfall of ES modules, only transpiling Vue templates (and TypeScript, etc.) on the fly. So there's no way to make the service worker work which requires a bundled application.

Also, part of the offline capability of the service worker relies on rendered Kirby pages. In local environment, Vite just proxies requests. The template used for the HTML entry point (`frontend/index.html`) differs from the one used in production (`site/snippets/vue-index.php`.

**Solution**: If you are using macOS with Laravel Valet, you can build your application, self-sign your local testing domain and then run your Kirby instance. This is the only way to debug to service worker for now. You can disable Terser on the minified service worker (edit `scripts/buildSw.js`) to find potential problems.

I've thoroughly tested the service worker over time and improved every bit, so it should work quite well. Of course, I'm open to suggestions! Why do you want to debug it, if I may ask?

Thanks for your issue!

**Comment by mrflix** [comment]
Thanks for the elaborate explanation. At the time of writing I was looking for an error and suspected its origin in the service worker. Turned out it came from somewhere else. Though I might still need to run the service worker offline because I want to add full offlice capabilities with prefetching of all assets (all image sources, source-sets, videos sources and all the json) and that might need some local debugging.

**Comment by johannschopplich** [comment]
I see. The service worker I created is quite flexible – you can add more cache buckets:

```js
const CACHE_KEYS = {
  // …
  RUNTIME: 'runtime'
}
```

And then cache everything in there: 

```js
// …
} else if (isImage) {
  stashInCache(CACHE_KEYS.IMAGES, request, copy)
} else {
  stashInCache(CACHE_KEYS.RUNTIME, request, copy)
}
```

Of course this just serves as an example. You can filter beforehand to sort assets into different cache buckets, rather than add everything into one bucket.

****

Testing the service worker offline works fine, just not from within the development server, but after compilation. Therefore I'm closing this. Would be happy to hear, how you extend this starterkit!
