### ISSUE TITLE
Replacing default image block snippet

### ISSUE THREAD

**Issue by fleshgordo** [johannschopplich/kirby-vue3-starterkit#42]
I am using Kirby blocks for my content and render it through my template page, let's say note.php like this:

```
$data = [
  'text' => ['html' => $page->text()->toBlocks()->toHtml()],
];

echo vite()->json($data);
```

I need to wrap some additional information to all my image tags and with a normal Kirby setup I could just create an image.php in `snippets/blocks/` inside the template folder and it would replace the image block snippet. However i don't see my changes to the image block if I try to fetch the json data from note.php

`curl http://localhost:8000/app/test/note-title.json`

For reference only this is the image.php

```
<?php

/** @var \Kirby\Cms\Block $block */
$alt     = $block->alt();
$caption = $block->caption();
$crop    = $block->crop()->isTrue();
$link    = $block->link();
$ratio   = $block->ratio()->or('auto');
$src     = null;

if ($block->location() == 'web') {
    $src = $block->src()->esc();
} elseif ($image = $block->image()->toFile()) {
    $alt = $alt ?? $image->alt();
    $src = $image->url();
    $id = $image->id();
}

?>
<?php if ($src): ?>
<figure<?= attr(['data-ratio' => $ratio, 'data-crop' => $crop], ' ') ?>>
  <?php if ($link->isNotEmpty()): ?>
  <a href="<?= esc($link->toUrl()) ?>">
    <img src="<?= $src ?>" alt="<?= $alt->esc() ?>">
  </a>
  <?php else: ?>
  <img src="<?= $src ?>" data-id="<?= $id ?>" alt="<?= $alt->esc() ?>">
  <?php endif ?>

  <?php if ($caption->isNotEmpty()): ?>
  <figcaption>
    <?= $caption ?>
  </figcaption>
  <?php endif ?>
</figure>
<?php endif ?>
```

**Comment by johannschopplich** [comment]
Kirby's internals of this starter kit stay untouched. Blocks should work as expected. Have you tried a different block, to create a minimal, reproducible example? Say, a custom line block.

**Comment by fleshgordo** [comment]
For testing I've added to templates/snippets/blocks/line.php:

`<hr style="border-top: 1px solid red;" />`

This should turn all line block elements into red, right? Still, in my json response I see only the standard <hr>

**Comment by johannschopplich** [comment]
Should be in `site/snippets/blocks/line.php`.

**Comment by fleshgordo** [comment]
GREAT! Works! Thank you so much!
