### ISSUE TITLE
Queries not working

### ISSUE THREAD

**Issue by Small-Systems** [johannschopplich/kirby-vue3-starterkit#49]
Route queries, used for the token for previewing drafts are not being passed correctly into the getPage function.
Query needs to be a rest parameter:

`async function getPage(id, { revalidate = false, ...query } = {})`

**Comment by johannschopplich** [comment]
Thanks for the feedback! Fixed in https://github.com/johannschopplich/kirby-vue3-starterkit/commit/8391f6c47fa50c69b4e233b8478a2f48888ae981.
