### ISSUE TITLE
Draft preview not working

### ISSUE THREAD

**Issue by mnelson-sg** [johannschopplich/kirby-vue3-starterkit#52]
Hello! I'm having an issue getting previewing a page in "Drafts" to work. Whenever a page is in "Draft" mode and I try to open the page, using the token generated by the CMS, the page goes to the 404/error page.

I'm not quite sure what other information you might need - please let me know!

**Comment by johannschopplich** [comment]
Hi! Are you using the latest version of this starter kit? Couldn't reproduce this behavior locally. I've changed the page status of `notes/exploring-the-universe` to draft, and it works – the token lets the page be visited.

Can you assure you're using the latest version of this project or provide a reproducible example?

**Comment by mnelson-sg** [comment]
Hey Johann, so sorry for the late response. I am using an old version of the starter kit - it seems I need to update to the latest version. I'll start on that today and I'm sure that it'll be working when I'm all up to date! Thanks for your help.

**Comment by johannschopplich** [comment]
No rush! I see. The feature was added in a later version of this project. 😊
